mqtt: #Configure connection to the MQTT broker
  host: IP_ADDRESS
  user: MQTT_USERNAME
  password: MQTT_PASSWORD
cameras:
  CAMERA_NAME: #Each camera is defined by starting it’s config with its name
    ffmpeg:
      inputs: # Each camera can have multiple paths defined, so that recording can be done in one resolution and detection in another
        - path: rtsp://IP_ADDRESS:PORT/STREAM_NAME #Video stream output URL from the camera
          roles: 
            - detect
            - rtmp
            - record
    objects:
      track: #Object types to track
        - person
        - car
    detect:
      width: 1024
      height: 576
    zones:
      ZONE_NAME: #Setup zones so that the location of motion can be reported
        coordinates: 122,125,231,576,1024,576,223,114
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 10 #Retain for ten days
    mode: active_objects #Only record detected objects that move
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  retain:
    default: 10
    mode: active_objects #Only take snapshots of detected objects that move
logger:
  default: info
motion:
  mask: #Setup motion zones that Frigate will exclude from motion detection
    - 65,0,258,0,267,104,100,130
